spring.main.banner-mode=off

logging.config=../logback-nais.xml

# Actuator
management.endpoints.web.exposure.include=prometheus,health


#Altinn
dokdistdpo.altinn.brokerserviceexternal.readtimeoutms=30000
dokdistdpo.altinn.brokerserviceexternal.connecttimeoutms=5000

dokdistdpo.altinn.brokerserviceexternalstreamed.readtimeoutms=60000
dokdistdpo.altinn.brokerserviceexternalstreamed.connecttimeoutms=5000