kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  filesFrom:
    - secret: {{ DOKDISTDPO_SECRET }}
      mountPath: /var/run/secrets/nais_secrets
  envFrom:
    - secret: {{ DOKDISTDPO_SECRET }}
  env:
    - name: JAVA_TRUSTSTORE_OPTIONS
      value: "-Djavax.net.ssl.trustStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.trustStorePassword=$(NAV_TRUSTSTORE_PASSWORD)"
    - name: JDK_JAVA_OPTIONS
      value: "-Djavax.net.ssl.keyStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.keyStorePassword=$(NAV_TRUSTSTORE_PASSWORD)
              -Djavax.net.ssl.keyStoreType=jks
              -XX:MaxRAMPercentage=75
              -XX:MaxHeapFreeRatio=55
              -XX:HeapDumpPath=/tmp
              $(JAVA_PROXY_OPTIONS) $(JAVA_TRUSTSTORE_OPTIONS)"
    - name: DOKDISTDPO_ENDPOINTS_DOKDISTADMIN_URL
      value: {{ DOKDISTDPO_ENDPOINTS_DOKDISTADMIN_URL }}
    - name: DOKDISTDPO_ENDPOINTS_DOKDISTADMIN_SCOPE
      value: {{ DOKDISTDPO_ENDPOINTS_DOKDISTADMIN_SCOPE }}
    - name: DOKDISTDPO_SERVICEREGISTRY_URL
      value: {{ DOKDISTDPO_SERVICEREGISTRY_URL }}
    - name: DOKDISTDPO_JURIDISKLOGG_URL
      value: {{ DOKDISTDPO_JURIDISKLOGG_URL }}
    - name: DOKDISTDPO_ALTINN_BROKERSERVICEEXTERNAL_ENDPOINTURL
      value: {{ DOKDISTDPO_ALTINN2_BROKERSERVICEEXTERNAL_ENDPOINTURL }}
    - name: DOKDISTDPO_ALTINN2_BROKERSERVICEEXTERNALSTREAMED_ENDPOINTURL
      value: {{ DOKDISTDPO_ALTINN2_BROKERSERVICEEXTERNALSTREAMED_ENDPOINTURL }}
    - name: NAV_VIRKSOMHETSSERTIFIKAT_CREDENTIALS
      value: {{ NAV_VIRKSOMHETSSERTIFIKAT_CREDENTIALS }}
    - name: NAV_VIRKSOMHETSSERTIFIKAT_KEY
      value: {{ NAV_VIRKSOMHETSSERTIFIKAT_KEY }}
    - name: DOKDISTMELLOMLAGER_PROJECTID
      value: {{ DOKDISTMELLOMLAGER_PROJECTID }}
    - name: DOKDISTMELLOMLAGER_BUCKET
      value: {{ DOKDISTMELLOMLAGER_BUCKET }}
    - name: DOKDISTMELLOMLAGER_KEYRING
      value: {{ DOKDISTMELLOMLAGER_KEYRING }}
    - name: DOKDISTMELLOMLAGER_KEYID
      value: {{ DOKDISTMELLOMLAGER_KEYID }}
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
    - name: DOKDISTDPO_MQ_GATEWAY_MANAGER_NAME
      value: {{ DOKDISTDPO_MQ_GATEWAY_MANAGER_NAME }}
    - name: DOKDISTDPO_MQ_GATEWAY_CHANNEL_NAME
      value: {{ DOKDISTDPO_MQ_GATEWAY_CHANNEL_NAME }}
    - name: DOKDISTDPO_MQ_GATEWAY_HOSTNAME
      value: {{ DOKDISTDPO_MQ_GATEWAY_HOSTNAME }}
    - name: DOKDISTDPO_MQ_GATEWAY_PORT
      value: "{{ DOKDISTDPO_MQ_GATEWAY_PORT }}"
    - name: DOKDISTDPO_QDIST015_DIST_TIL_DPO_QUEUENAME
      value: {{ DOKDISTDPO_QDIST015_DIST_TIL_DPO_QUEUENAME }}
    - name: DOKDISTDPO_QDIST015_FUNK_FEIL_QUEUENAME
      value: {{ DOKDISTDPO_QDIST015_FUNK_FEIL_QUEUENAME }}
    - name: DOKDISTSENTRALPRINT_QDIST009_DIST_S_PRINT_QUEUENAME
      value: {{ DOKDISTSENTRALPRINT_QDIST009_DIST_S_PRINT_QUEUENAME }}
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/run/secrets/nais_secrets/gcloud_serviceaccount.json"
    - name: MASKINPORTEN_TOKEN_ENDPOINT
      value: {{ MASKINPORTEN_TOKEN_ENDPOINT }}
    - name: MASKINPORTEN_ISSUER
      value: {{ MASKINPORTEN_ISSUER }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  webproxy: true
  leaderElection: true
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: {{ MEMORY_LIMITS }}
    requests:
      cpu: 60m
      memory: {{ MEMORY_REQUESTS }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: {{ NAV_VIRKSOMHETSSERTIFIKAT_VAULT }}
        mountPath: "/secrets/virksomhetssertifikat"
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: altinn:broker.write
        - name: altinn:serviceowner
        - name: altinn:authentication/systemregister.write