kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  webproxy: true
  leaderElection: true
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 3Gi
    requests:
      memory: 1Gi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "elastic-apm"
  azure:
    application:
      enabled: true